import numpy as np
import cv2
import matplotlib.pyplot as plt
img = cv2.imread("house.jpg")
if img is None:
    print("Error: Could not load image. Please check the file name or path.")
else:
    rgb_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    ret, thresh = cv2.threshold(gray,0,255,cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
    kernel = np.ones((2, 2), np.uint8)
    closing = cv2.morphologyEx(thresh,cv2.MORPH_CLOSE,kernel,iterations=2)
    sure_bg = cv2.dilate(closing,kernel,iterations=3)
    plt.figure(figsize=(12, 8))
    plt.subplot(2, 3, 1)
    plt.imshow(rgb_img)
    plt.title("Original Image")
    plt.axis("off")
    plt.subplot(2, 3, 2)
    plt.imshow(gray, cmap="gray")
    plt.title("Grayscale Image")
    plt.axis("off")
    plt.subplot(2, 3, 3)
    plt.imshow(thresh, cmap="gray")
    plt.title("Otsu's Threshold")
    plt.axis("off")
    plt.subplot(2, 3, 4)
    plt.imshow(closing, cmap="gray")
    plt.title("Morphological Closing")
    plt.axis("off")
    plt.subplot(2, 3, 5)
    plt.imshow(sure_bg, cmap="gray")
    plt.title("Dilation")
    plt.axis("off")
    plt.tight_layout()
    plt.show()
    cv2.imwrite("dilation.png", sure_bg)
    print("Dilation image saved as dilation.png")
