import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input,Embedding,Bidirectional,LSTM,Dense,Concatenate
encoder_data=np.array([[1,2,3,4,0],[1,5,6,7,0],[1,8,9,10,0],[1,11,12,13,0]])
decoder_data=encoder_data.copy()
target=np.expand_dims(decoder_data,-1)
encoder_inputs=Input(shape=(None,))
encoder_embedding=Embedding(20,16)(encoder_inputs)
encoder=Bidirectional(LSTM(16,return_state=True))
_,fh,fc,bh,bc=encoder(encoder_embedding)
state_h=Dense(16,activation="tanh")(Concatenate()([fh,bh]))
state_c=Dense(16,activation="tanh")(Concatenate()([fc,bc]))
decoder_inputs=Input(shape=(None,))
decoder_embedding=Embedding(20,16)(decoder_inputs)
decoder=LSTM(16,return_sequences=True)
decoder_output=decoder(decoder_embedding,initial_state=[state_h,state_c])
output=Dense(20,activation="softmax")(decoder_output)
model=Model([encoder_inputs,decoder_inputs],output)
model.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=["accuracy"])
model.fit([encoder_data,decoder_data],target,epochs=2,batch_size=2,verbose=1)
prediction=model.predict([encoder_data[:1],decoder_data[:1]],verbose=0)
print("Input Shape:",encoder_data.shape)
print("Prediction Shape:",prediction.shape)
print("Bidirectional RNN Encoder-Decoder executed successfully.")
